name: angel_aqueduct
description: Embed Aqueduct within Angel. Use this to wrap existing server code.
homepage: https://github.com/angel-dart/aqueduct
name: angel_aqueduct
version: 2.0.0
dependencies:
  angel_framework: ^2.0.0
  path: ^1.0.0
  aqueduct: ^3.0.0
dev_dependencies:
  angel_test: ^2.0.0
  aqueduct_static: ^3.0.0
  test: ^1.0.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
